sudo: false
language: node_js
  - '6'
  - '8'
  - '10'
  - '12'
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run test
  - npm run build

